name: "Docker Image Build"
description: " "
author: "NicolasSarko@github.com"

inputs:
  MY_NAME:
    description: " "
    required: true
    default: " "

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
