name: "CI"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1
      
      - name : ls
        run : ls
        
      - name : cd
        run : cd action-a
        
      - name: Permissions
        run : chmod -r 777

      - name: Test
        run: bats test.sh 
