name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nicolassarko/repodevops:$(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/repodevops
      
    - name: Get latest tag
      id: latest_tag
      uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
      with:
        org: 'nicolassarko'  # Docker Hub user or organisation name
        repo: 'repodevops'  # Docker Hub repository name

    # Optionally check the tag we got back
    - name: Check outputs
      run: |
        echo "Latest Image Tag - ${{ steps.latest_tag.outputs.tag }}"
