name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  

    runs-on: ubuntu-latest
    env:
          tag: ${{ env.tag }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: docker build . --file action-a/Dockerfile --tag nicolassarko/repodevops:$tag
    - name: Docker Push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/repodevops:$tag
    
